### ISSUE TITLE
Output warnings instead of failing the build

### ISSUE THREAD

**Issue by nickstolwijk** [jonathanlermitage/oga-maven-plugin#18]
I would like to add this plugin to our standard build to make developers aware of these relocations. Unfortunately, the plugin only supports the failing of the build instead of just output warnings.

Could it be an option to not fail the build?

**Comment by jonathanlermitage** [comment]
Good idea. Will publish a new release soon (1.3.0).

**Comment by jonathanlermitage** [comment]
1.3.0 released and published to maven central. It should be visible in a few days (you can check https://search.maven.org/artifact/biz.lermitage.oga/oga-maven-plugin).  
You can configure the plugin this way:  
```
            <plugin>
                <groupId>biz.lermitage.oga</groupId>
                <artifactId>oga-maven-plugin</artifactId>
                <version>1.3.0</version>
                <configuration>
                    <failOnError>false</failOnError>
                </configuration>
            </plugin>
```

**Comment by jonathanlermitage** [comment]
Done, you can upgrade to 1.3.0 ;-) @nickstolwijk
