### ISSUE TITLE
[feaure request] make the og-definitions.json configurable

### ISSUE THREAD

**Issue by dilbertside** [jonathanlermitage/oga-maven-plugin#2]
Hi,

Thanks for your plugin contribution, it is useful.
It would be even more useful if we could add an alternative `og-definitions.json` which would be either concatenated with the one provided with the plugin and/or one with either no public libraries or so old libraries that would make no sense to add in this very public definition file.

If this feature already exists, it would be nice to document it.

Here an example how maven-checkstyle-plugin add the configurable definitions for checkstyle configuration.

```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-checkstyle-plugin</artifactId>
	<executions>
		<execution>
			<id>validate</id>
			<phase>validate</phase>
			<goals>
				<goal>check</goal>
			</goals>
			<configuration>
				<configLocation>./</configLocation>
				<suppressionsLocation>./</suppressionsLocation>
			</configuration>
		</execution>
	</executions>
</plugin>
```

**Comment by jonathanlermitage** [comment]
@dilbertside Thx for this idea. Implemented. I will release 1.1.0 asap.

**Comment by jonathanlermitage** [comment]
Published. Artifact should be available on Maven Central within 24~48h (check https://search.maven.org/artifact/biz.lermitage.oga/oga-maven-plugin).

**Comment by jonathanlermitage** [comment]
PS: Ill try to add an option to merge multiple definition files later.
