### ISSUE TITLE
false-positive rate

### ISSUE THREAD

**Issue by doroniz** [jonathanlermitage/oga-maven-plugin#21]
Hi, I'm considering using this plugin does anyone know the false-positive rate?

**Comment by jonathanlermitage** [comment]
Hi @doroniz 
I have no idea of false-positives. The list of relocated is built from the maven index and some manual work, so there should not be false-positive.  
Meanwhile, some users may want to stick to old artifacts. Per example, you may not be ready to move from java-ee to jakarta-ee. I am working on an ignore-list (see https://github.com/jonathanlermitage/oga-maven-plugin/issues/19), this way you can continue to use deprecated artifacts and the oga plugin won't generate warn/error messages.

**Comment by doroniz** [comment]
OK, got it.
Thanks a lot.
