### ISSUE TITLE
relocations for plugins

### ISSUE THREAD

**Issue by froque** [jonathanlermitage/oga-maven-plugin#23]
> What is the difference between dependency-maven-plugin and maven-dependency-plugin?
>  Actually, they are the same, it's just that it was moved and renamed. The dependency-maven-plugin is hosted at Mojo while maven-dependency-plugin is hosted at Apache. The recommended plugin to use is the maven-dependency-plugin. 

https://maven.apache.org/plugins/maven-dependency-plugin/faq.html#plugin_name

Shoud this oga-maven-plugin also analyze other maven plugins ?

**Comment by jonathanlermitage** [comment]
@froque I think this is a good idea :+1:  
Maven plugin coordinates can move too :-D

**Comment by froque** [comment]
another relocated plugin: pl.project13.maven:git-commit-id-plugin -> io.github.git-commit-id:git-commit-id-maven-plugin

https://github.com/git-commit-id/git-commit-id-maven-plugin#relocation-of-the-project

https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/465

**Comment by jonathanlermitage** [comment]
Implemented, and _pl.project13.maven:git-commit-id-plugin -> io.github.git-commit-id:git-commit-id-maven-plugin_ added to definitions.  
Will publish 1.5.4 release soon.

**Comment by jonathanlermitage** [comment]
Note: the definition file manages dependencies and plugins. It is probably not necessary to have two files.  
The generated report indicates whether the deprecated artifacts are dependencies or plugins.

**Comment by froque** [comment]
@jonathanlermitage nice. What about dependency-maven-plugin ?

**Comment by jonathanlermitage** [comment]
Yeah, you're right. Definitions file updated :-)
