### ISSUE TITLE
request skip option

### ISSUE THREAD

**Issue by CasperNLD** [jonathanlermitage/oga-maven-plugin#35]
Hi, 
I like to request a skip option, for two reasons:
- In the cases where I do not have a internet connection, I would like the possibility to skip the check on the command line.
- In our multi-branch pipeline we first want to know if the feature is compiling successfully, and in a later step on this check with the enforcer checks.

Since I am not able to create a pull request, please consider my supplied ZIP file

[feature.zip](https://github.com/jonathanlermitage/oga-maven-plugin/files/7384006/feature.zip)

**Comment by jonathanlermitage** [comment]
thx!

**Comment by CasperNLD** [comment]
Thanks!
