### ISSUE TITLE
Support for additional migrations without overriding community contributed migrations

### ISSUE THREAD

**Issue by pwhittlesea** [jonathanlermitage/oga-maven-plugin#47]
Having the migrations file managed within this Github repo is fantastic as users of this module can benefit from the [community contributions](https://raw.githubusercontent.com/jonathanlermitage/oga-maven-plugin/master/uc/og-definitions.json) to relocated dependencies.

As a user I have many libraries which I maintain myself and I would love to have a 'business-wide' definition file.
I can specify the `ogDefinitionsUrl` property to point to a self-managed definitions file but I then lose out on updates to the community contributions.

What would be great is if I had a way to specify an 'additions' file which meant the plugin pulled in `ogDefinitionsUrl` and then **added** in my extra definitions. Maybe a property called `ogAdditionalDefinitionsUrl`?

So if:
- `ogDefinitionsUrl` was set to `https://raw.githubusercontent.com/jonathanlermitage/oga-maven-plugin/master/uc/og-definitions.json`
- `ogAdditionalDefinitionsUrl` was set to `https://smallbusiness.lan/my-gitlab-instance/business-config/og-definitions.json`

And the file at `ogDefinitionsUrl` contained:
```json
{
    "version": "22",
    "date": "2022/07/07",
    "migration": [
        {
            "old": "acegisecurity",
            "new": "org.acegisecurity"
        }
    ]
}
```

And file at `ogAdditionalDefinitionsUrl` contained:
```json
{
    "version": "22",
    "date": "2022/07/07",
    "migration": [
        {
            "old": "lan.smallbusiness:my-framework",
            "new": "lan.smallbusiness:my-relocated-framework"
        }
    ]
}
```

Then our 'effective' migrations would be:
- `acegisecurity` -> `org.acegisecurity`
- `lan.smallbusiness:my-framework` -> `lan.smallbusiness:my-relocated-framework`

Before I jump in and try contribute some code what do people think? Any objections?

**Comment by froque** [comment]
That looks a fine addition to me

**Comment by jonathanlermitage** [comment]
I agree :+1:

**Comment by jonathanlermitage** [comment]
Implemented. Will write documentation and publish a new release soon.
