### ISSUE TITLE
reactivex

### ISSUE THREAD

**Issue by froque** [jonathanlermitage/oga-maven-plugin#59]
- `io.reactivex` -> `io.reactivex.rxjava2`
   - https://github.com/ReactiveX/RxJava/pull/4031
   - https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0
 - `io.reactivex.rxjava2` -> `io.reactivex.rxjava3`
   - https://github.com/ReactiveX/RxJava/pull/6421
   - https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0

**Comment by jonathanlermitage** [comment]
Thx!  
Definitions file updated.
