### ISSUE TITLE
Add GitHub issue template form for new entries

### ISSUE THREAD

**Issue by timtebeek** [jonathanlermitage/oga-maven-plugin#72]
Hi! Love the project here; I'm wondering if it would help to [add a GitHub issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) for new submissions. To start with that might help to standardize new submissions. Once established one could even [automate the creation of a PR](https://github.com/orgs/community/discussions/6838) from a filled in issue form, to further reduce the work (even if it's likely minimal to start with).

**Comment by jonathanlermitage** [comment]
Hi! Sure, it would be great. Contributions are highly appreciated 😀

**Comment by timtebeek** [comment]
Sure! Pushed up to https://github.com/jonathanlermitage/oga-maven-plugin/pull/73
